### ISSUE TITLE
elInput.intlTelInput is not a function

### ISSUE THREAD

**Issue by gomesNazareth** [topguru/ng2-intl-tel-input#1]
Hi a am getting  below error when the following code runs 
this.elInput = jQuery(this.el).find('ng2intltelinput');
   this.elInput.intlTelInput();

platform-browser.umd.js:962 ORIGINAL EXCEPTION: TypeError: this.elInput.intlTelInput is not a function

**Comment by 1notchdev** [comment]
Hi,

Sorry for response lately.
It should be as following.

this.elInput = jQuery(this.el).find('.ng2intltelinput');

You are missed "." in selector "ng2intltelinput".

Thanks

**Comment by SnehaAwasthi** [comment]
It still throws the same error.Can u please guide?
